### PR TITLE
[WIP] Provision contract fields for authz (contract update afterwards)

### LINKED ISSUE #4041: [control-plane] Provision allowed Subjects in the contract
The in #4040 added fields need to be provisioned with the correct values, so that the data-plane has this information too.

**Additional hints for new contributors before starting with this issue:**

1. When the issue has the `Draft` status, the issue is subject to change and thus should not be started to be worked on
2. Make sure you've read and understood the [CONTRIBUTING.md](https://github.com/knative-extensions/eventing-kafka-broker/blob/main/CONTRIBUTING.md) guidelines
3. Make sure you're able to [run Knative Eventing locally](https://github.com/knative/eventing/blob/main/DEVELOPMENT.md#create-a-cluster-and-a-repo) with [Knative Eventing Kafka](https://github.com/knative-extensions/eventing-kafka-broker/blob/main/DEVELOPMENT.md) and [run at least the unit tests](https://github.com/knative-extensions/eventing-kafka-broker/blob/main/DEVELOPMENT.md#run-unit-tests). 
4. Feel free to raise any questions you have either directly here in the issue, in the [#knative-eventing Slack channel](https://cloud-native.slack.com/archives/C04LMU33V1S) or join the [Eventing Workgroup Meeting / Office Hours](https://github.com/knative/community/blob/main/working-groups/WORKING-GROUPS.md#eventing)
5. When you feel comfortable with this issue, feel free to assign it to you (e.g. by commenting `/assign`). Please be aware that we might unassign you, if we don't see any progress from your side to give other contributors also a chance to work on this issue.

### PR DESCRIPTION
**Pull request by creydr**
Fixes #4041

## Proposed Changes

- provision applying EventPolicies from Broker, KafkaChannel and KafkaSink in their contracts

Same as #4064, except that it refactors the Broker, KafkaChannel and KafkaSink reconcilers to do the contract update at the end of the reconcilation. This leads to having the .status fields which are part of the contract (e.g. OIDC audience or applying EventPolicies) are being updated directly in the contract.
Anyhow, the probing con only be done after the contract update, as otherwise the data-plane is not aware of the resource and this would lead to 404 on probing the resources endpoint. This has the side effect, that the resource will be marked as addressable, before the probe run (anyhow we have the `ProbeSucceeded` condition, which can render the resource as NotReady anyhow)

### CODE REVIEW

**Comment by Cali0707** [comment]
> Anyhow, the probing con only be done after the contract update, as otherwise the data-plane is not aware of the resource and this would lead to 404 on probing the resources endpoint. This has the side effect, that the resource will be marked as addressable, before the probe run (anyhow we have the ProbeSucceeded condition, which can render the resource as NotReady anyhow)

@creydr as far as I can tell from the code, we don't use the `.status.address(es)` field when doing the contract update. Maybe we can compute the addresses, but not set them on the resource until after the probing is successful and instead just keep them in variables somewhere? I might also be missing something...

**Comment by creydr** [comment]
We use the audience and later the event policies from the status. So this "safes" us one reconciliation. But I might miss here something too...

**Comment by creydr** [comment]
Closing as discussed with @pierDipi, as sources can start to send events to addressables as soon as they have an address (they don't check the ready condition), so we should set the addressable condition, only when the addressable is ready to accept events.

**Pull request closed without merging**
