### PR TITLE
Migrate to kube_codegen.sh

### PR DESCRIPTION
**Pull request by pierDipi**
As per title

### CODE REVIEW

**Comment by pierDipi** [comment]
```
 rbac.go:40: failed to create resource an error on the server ("Internal Server Error: \"/apis/rbac.authorization.k8s.io/v1/namespaces/test-ukvbbjir/rolebindings\": the server is currently unable to handle the request") has prevented the request from succeeding - Resource:
```

**Comment by pierDipi** [comment]
```
--- Cleaning up generated code' --dest=/logs/artifacts/junit_6fKyF10j.xml
/home/prow/go/src/knative.dev/eventing-kafka-broker/test/../vendor/knative.dev/hack/library.sh: line 697: /root/.gvm/gos/go1.22.6/bin/go: Argument list too long
+ return 1
```

**Comment by pierDipi** [comment]
@cardil can you help here? I don't know what's the issue and I can't reproduce locally

**Review by creydr — COMMENTED** [review]
tested via 
```
find control-plane/pkg/apis -name 'zz_generated*' -delete
rm -r  control-plane/pkg/client/ 
./hack/update-codegen.sh
```
And no changes

/lgtm

**Pull request merged**
