### PR TITLE
Allow enabling sarama logging and disabling client pool

### PR DESCRIPTION
**Pull request by pierDipi**
Add 3 new environment variables:
```
ENABLE_SARAMA_LOGGER       (default: false)
ENABLE_SARAMA_DEBUG_LOGGER (default: false)
ENABLE_SARAMA_CLIENT_POOL  (default: true)
```

I want to see if these help with giving more information to debug this issue: https://github.com/knative-extensions/eventing-kafka-broker/issues/4091

### CODE REVIEW

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Review by creydr — COMMENTED** [review]
/lgtm

**Pull request merged**
