### PR TITLE
Update Quarkus 3.2.x and align the vertx lib to it 

### PR DESCRIPTION
**Pull request by matzew**
Fixes #

## Proposed Changes

- contains the Quarkus bump from #3413
- also aligns to vertx 4.4.4 (since our Quarkus 3.2 uses that)

FWIW, there is a newer version: 4.4.6, but that's not aligned with our version of Quarkus.....

**Release Note**

```release-note

```

**Docs**

### CODE REVIEW

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Review by creydr — APPROVED** [review]
/lgtm

**Pull request merged**
