### PR TITLE
Provision contract with OIDC information

### LINKED ISSUE #3572: [control-plane]: Provision Audience and OIDCServiceAccountName fields in contract
The in #3571 added fields (OIDCServiceAccountName and Audience of Ingress, Destination, Reply and DLS) need to be provisioned with the correct values, so the data-plane has this information too.

**Additional Information:**
* Requires #3520 and #3521 too

### PR DESCRIPTION
**Pull request by creydr**
Fixes #3572 (follow up on #3571)

## Proposed Changes

- Update contract with OIDC information. This includes:
  - Audience of the Destination
  - Audience of the Reply
  - Audience of the Dead-Letter-Sink
  - OIDCServiceAccountName
  - Audience of the ingress

**Release Note**

```release-note
none
```

### CODE REVIEW

**Comment by creydr** [comment]
Can be tested in the following way (currently not for Broker & Triggers, as this is still WIP (#3600)):

1. Create services (subscriber, reply, DLS):
```
$ kn service create event-display --image gcr.io/knative-releases/knative.dev/eventing/cmd/event_display
$ kn service create my-reply --image gcr.io/knative-releases/knative.dev/eventing/cmd/event_display
$ kn service create my-dls --image gcr.io/knative-releases/knative.dev/eventing/cmd/event_display
```
2. Create a KafkaChannel (having configured to be a KafkaChannel the default):
```
apiVersion: messaging.knative.dev/v1
kind: Channel            
metadata:  
  name: my-kafka-channel
```
3. Create a Subscription:
```
apiVersion: messaging.knative.dev/v1
kind: Subscription
metadata:
  name: my-sub
spec:
  channel:
    apiVersion: messaging.knative.dev/v1beta1
    kind: KafkaChannel
    name: my-kafka-channel
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display
    audience: ed-audience
  delivery:
    deadLetterSink:
      ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: my-dls
      audience: dls-audience
  reply:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: my-reply
    audience: reply-audience
```

Then we see in the `kafka-channel-channels-subscriptions` the following:
```
k -n knative-eventing get cm kafka-channel-channels-subscriptions -ojsonpath='{.binaryData.data}' | base64 -d | jq .resources
[
  {
    "uid": "bc395fb8-6812-4429-8127-10c7a77e7bc6",
    "topics": [
      "knative-messaging-kafka.default.my-kafka-channel"
    ],
    "bootstrapServers": "my-cluster-kafka-bootstrap.kafka:9092",
    "ingress": {
      "path": "/default/my-kafka-channel",
      "host": "my-kafka-channel-kn-channel.default.svc.cluster.local",
      "audience": "messaging.knative.dev/kafkachannel/default/my-kafka-channel"
    },
    "egresses": [
      {
        "consumerGroup": "kafka.default.my-kafka-channel.6c26bb94-5208-458d-90b4-a46e58dd8d42",
        "destination": "http://event-display.default.svc.cluster.local",
        "destinationAudience": "ed-audience",
        "replyUrl": "http://my-reply.default.svc.cluster.local",
        "replyUrlAudience": "reply-audience",
        "uid": "6c26bb94-5208-458d-90b4-a46e58dd8d42",
        "egressConfig": {
          "deadLetter": "http://my-dls.default.svc.cluster.local",
          "deadLetterAudience": "dls-audience"
        },
        "deliveryOrder": "ORDERED",
        "reference": {
          "uuid": "6c26bb94-5208-458d-90b4-a46e58dd8d42",
          "namespace": "default",
          "name": "my-sub"
        },
        "oidcServiceAccountName": "my-sub-oidc-messaging.knative.dev-subscription"
      }
    ],
    "reference": {
      "uuid": "bc395fb8-6812-4429-8127-10c7a77e7bc6",
      "namespace": "default",
      "name": "my-kafka-channel",
      "kind": "KafkaChannel",
      "groupVersion": "messaging.knative.dev/v1beta1"
    }
  }
]
```
note the destinationAudience, replyAudience, deadLetterAudience and the oidcServiceAccount.

Same was tested for a KafkaSource:
1. Create Tropic and KafkaSource:
```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic  
metadata:          
  name: knative-demo-topic
  namespace: kafka                           
  labels:                          
    strimzi.io/cluster: my-cluster           
spec:                 
  partitions: 3           
  replicas: 1
  config:   
    retention.ms: 7200000               
    segment.bytes: 1073741824
---
apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource 
metadata:          
  name: kafka-source      
spec:                                        
  consumerGroup: knative-group     
  bootstrapServers:                          
  - my-cluster-kafka-bootstrap.kafka:9092
  topics:                 
  - knative-demo-topic
  sink:     
    ref:                                
      apiVersion: serving.knative.dev/v1                                                         
      kind: Service      
      name: event-display 
    audience: ed-audience
```
Resulted in the following contract:
```
$ k -n knative-eventing get cm kafka-source-dispatcher-0 -ojsonpath='{.binaryData.data}' | base64 -d | jq .resources
[
  {
    "uid": "bd71e8cc-e3ba-4d22-8542-307e2a1d37bd",
    "topics": [
      "knative-demo-topic"
    ],
    "bootstrapServers": "my-cluster-kafka-bootstrap.kafka:9092",
    "egresses": [
      {
        "consumerGroup": "knative-group",
        "destination": "http://event-display.default.svc.cluster.local",
        "destinationAudience": "ed-audience",
        "discardReply": {},
        "uid": "bd71e8cc-e3ba-4d22-8542-307e2a1d37bd",
        "egressConfig": {
          "retry": 10,
          "backoffDelay": "300",
          "timeout": "600000"
        },
        "deliveryOrder": "ORDERED",
        "reference": {
          "uuid": "b08d105d-9f36-4818-b86e-6401ec50ad00",
          "namespace": "default",
          "name": "kafka-source"
        },
        "vReplicas": 1,
        "featureFlags": {
          "enableRateLimiter": true,
          "enableOrderedExecutorMetrics": true
        },
        "oidcServiceAccountName": "my-source-oidc-sa"
      }
    ],
    "multiAuthSecret": {},
    "reference": {
      "uuid": "b08d105d-9f36-4818-b86e-6401ec50ad00",
      "namespace": "default",
      "name": "kafka-source"
    }
  }
]
```

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Comment by creydr** [comment]
@pierDipi I needed to rebase and then fix a unit test. Can you recheck?

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
