### PR TITLE
LoomKafkaProducer|Consumer let the background thread finish itself

### PR DESCRIPTION
**Pull request by maschmid**
Follows up to https://github.com/knative-extensions/eventing-kafka-broker/pull/3957  , but for LoomKafkaProducer, and unifies the approach

Instead of interrupting the `BlockingQueue::take`, we just use `poll` in the background thread, so we don't have to deal with interrupting the thread, so we now don't accidentally interrupt the actual processing of the queued tasks.

Instead of waiting for the Thread to be marked as "finished", we just wait by `Thread::join`. The only way it would block forever, is if the processing of the task would wait forever.

## Proposed Changes

- :broom: LoomKafkaProducer|Consumer let the background thread finish itself

### CODE REVIEW

**Comment by maschmid** [comment]
actually, we still need to interrupt the `eventQueue.take()`

**Comment by maschmid** [comment]
/test channel-integration-tests-ssl

https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative-extensions_eventing-kafka-broker/4013/channel-integration-tests-ssl_eventing-kafka-broker_main/1817914303898980352 

TestEventTransformationForSubscription looks like same error as in yesterdays nightly https://prow.knative.dev/view/gs/knative-prow/logs/nightly_eventing-kafka-broker_main_periodic/1817493539722891264 , assuming flake

**Comment by maschmid** [comment]
https://storage.googleapis.com/knative-prow/pr-logs/pull/knative-extensions_eventing-kafka-broker/4017/upgrade-tests_eventing-kafka-broker_main/1818572261553082368/artifacts/upgrade-test-namespace-logs/eventing-e2e16/kafka-broker-dispatcher-0-kafka-broker-dispatcher.log

That one is kind of weird

{"@timestamp":"2024-07-31T09:33:21.431Z","@version":"1","message":"Unhandled exception","logger_name":"io.vertx.core.impl.ContextImpl","thread_name":"vert.x-eventloop-thread-3","level":"ERROR","level_value":40000,"stack_trace":"java.lang.UnsupportedOperationException: null\n\tat dev.knative.eventing.kafka.broker.dispatcher.impl.consumer.InvalidCloudEvent.getSpecVersion(InvalidCloudEvent.java:49)\n\tat io.cloudevents.core.builder.CloudEventBuilder.from(CloudEventBuilder.java:314)\n\tat dev.knative.eventing.kafka.broker.dispatcher.impl.consumer.CloudEventOverridesMutator.apply(CloudEventOverridesMutator.java:38)\n\tat dev.knative.eventing.kafka.broker.dispatcher.impl.consumer.CloudEventOverridesMutator.apply(CloudEventOverridesMutator.java:28)\n\tat dev.knative.eventing.kafka.broker.dispatcher.impl.RecordDispatcherMutatorChain.dispatch(RecordDispatcherMutatorChain.java:42)\n\tat dev.knative.eventing.kafka.broker.dispatcher.impl.consumer.UnorderedConsumerVerticle.handleRecords(UnorderedConsumerVerticle.java:133)\n\tat dev.knative.eventing.kafka.broker.dispatcher.impl.consumer.UnorderedConsumerVerticle.lambda$poll$1(UnorderedConsumerVerticle.java:103)\n\tat io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:279)\n\tat io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:261)\n\tat io.vertx.core.impl.ContextInternal.lambda$runOnContext$0(ContextInternal.java:59)\n\tat io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)\n\tat io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)\n\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)\n\tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n\tat java.base/java.lang.Thread.run(Unknown Source)\n"}

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
