### PR TITLE
[release-1.11] Upgrade to latest dependencies

### PR DESCRIPTION
**Pull request by Leo6Leo**
Modified version of:
https://github.com/knative-extensions/eventing-kafka-broker/pull/3393#issuecomment-1775703985

The extra change:
https://github.com/knative-extensions/eventing-kafka-broker/pull/3321/commits/55620219712c51bb07bc70f338b73d6c7bcfb307

Current having the issue in the tests, KafkaSource deletion error. Fixing WIP https://github.com/knative-extensions/eventing-kafka-broker/pull/3443

### CODE REVIEW

**Review by matzew — APPROVED** [review]
/lgtm
/approve

/retest

**Comment by pierDipi** [comment]
Thank you @Leo6Leo !

**Pull request merged**
