### PR TITLE
Provision delivery format in contract

### LINKED ISSUE #3970: Delivery format: add and provision `format` field to EgressConfig in contract
**Problem**
To support dispatching events in the format specified in the `format` field being added into the delivery spec of components, we need to add a field into the contract, and then provision that field from the control plane.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**
Unit tests indicating that the reconciler is setting the contract properly

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve? 1-2

**Additional context (optional)**
Add any other context about the feature request here.
- Parent issue: https://github.com/knative/eventing/issues/8057
- Required before this can be worked on: https://github.com/knative/eventing/issues/8073

### PR DESCRIPTION
**Pull request by Cali0707**
Fixes #3970 

## Proposed Changes

- Add the `format` field to the egress config

### CODE REVIEW

**Comment by Cali0707** [comment]
@matzew I've rebased this to only have the relevant changes, can you recheck?

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Comment by Cali0707** [comment]
/cc @matzew 

While going through the data plane changes I realized I needed to essentially re-do the changes in this PR so since the data plane changes are isolated I added them here as well instead

I'll add unit tests and an e2e test later, would you mind taking a look at the data plane code and letting me know if the approach I'm taking makes sense?

**Pull request closed without merging**
