### PR TITLE
KafkaCat was renamed to Kcat, and is on a newer version

### PR DESCRIPTION
**Pull request by matzew**
## Proposed Changes

- as per title, some updates on maintaining the kafkcat/kcat version

**Release Note**

```release-note

```

**Docs**

### CODE REVIEW

**Review by pierDipi — COMMENTED** [review]
```
containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "kafkacat": executable file not found in $PATH: unknown,StartedAt:1970-01-01 00:00:00 +0000 UTC,FinishedAt:2024-02-15 09:28:51 +0000 
```
Error in CI

**Comment by matzew** [comment]
thanks!

will check the binary is actyally called `kcat` now :-)

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
