### PR TITLE
Remove receiver-vertx and dispatcher-vertx modules

### PR DESCRIPTION
**Pull request by pierDipi**
After #3557 we are using Loom modules, so we can now remove the old modules based on vertx-kafka-clients

### CODE REVIEW

**Review by Cali0707 — APPROVED** [review]
/lgtm

**Comment by pierDipi** [comment]
/cc @creydr @Cali0707 

I rebased the PR since there were conflicts

**Review by Cali0707 — APPROVED** [review]
/lgtm

**Comment by Cali0707** [comment]
@pierDipi the upgrades should be fixed by #3868

**Pull request merged**
