### PR TITLE
Fix CI flakes

### PR DESCRIPTION
**Pull request by pierDipi**
- Migrate back `kafka-broker-receiver` for Brokers to deployments as we don't need statefulsets
- Use atomics for producer's `ReferenceCounter`
- Detect audience and identity SA changes on the data plane
- Return early if Producer.send returns an exception

### CODE REVIEW

**Comment by Cali0707** [comment]
@pierDipi it looks like for some reason the `kafka-broker-receiver-0` pod was restarted multiple times (from the logs there are 6 separate sets of them) in the [most recent test run](https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative-extensions_eventing-kafka-broker/3852/reconciler-tests_eventing-kafka-broker_main/1782762362281922560). I'm not sure what would be causing this

**Comment by Cali0707** [comment]
@pierDipi I think there is something weird happening in the receiver. I found these logs in the most recent failed tests:
```
{"@timestamp":"2024-04-23T18:35:56.13Z","@version":"1","message":"Resource not found path=/test-yoinakky/kafka-broker-mylhzxyo host=kafka-broker-ingress.knative-eventing.svc:8080 hostHeader=kafka-broker-ingress.knative-eventing.svc:8080","logger_name":"dev.knative.eventing.kafka.broker.receiver.impl.ReceiverVerticle","thread_name":"vert.x-eventloop-thread-4","level":"WARN","level_value":30000,"path":"/test-yoinakky/kafka-broker-mylhzxyo","host":"kafka-broker-ingress.knative-eventing.svc:8080","hostHeader":"kafka-broker-ingress.knative-eventing.svc:8080"}
{"@timestamp":"2024-04-23T18:36:14.591Z","@version":"1","message":"[Producer clientId=producer-8] Error while fetching metadata with correlation id 18036 : {knative-broker-test-yoinakky-kafka-broker-dnxsanim=UNKNOWN_TOPIC_OR_PARTITION, knative-broker-test-yoinakky-kafka-broker-xifvszir=UNKNOWN_TOPIC_OR_PARTITION, knative-broker-test-yoinakky-kafka-broker-mylhzxyo=UNKNOWN_TOPIC_OR_PARTITION, knative-broker-test-yoinakky-kafka-broker-bkvnydki=UNKNOWN_TOPIC_OR_PARTITION, knative-broker-test-yoinakky-kafka-broker-vpjsvlol=UNKNOWN_TOPIC_OR_PARTITION, knative-broker-test-yoinakky-kafka-broker-ledflhkr=UNKNOWN_TOPIC_OR_PARTITION, knative-broker-test-yoinakky-kafka-broker-lkiqrpgt=UNKNOWN_TOPIC_OR_PARTITION}","logger_name":"org.apache.kafka.clients.NetworkClient","thread_name":"kafka-producer-network-thread | producer-8","level":"WARN","level_value":30000}```

What I find weird about this is that there is a missing resource for `/test-yoinakky/kafka-broker-mylhzxyo`, but there is also an `UNKNOWN_TOPIC_OR_PARTITION` for the same resource. So, somehow the producer knows about it but can't fetch metadata, but there is no resource in the host mapping and path mapping

**Comment by pierDipi** [comment]
> @pierDipi I think there is something weird happening in the receiver. I found these logs in the [most recent failed tests](https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative-extensions_eventing-kafka-broker/3852/reconciler-tests-namespaced-broker_eventing-kafka-broker_main/1782825644011294720):
> 
> ```
> {"@timestamp":"2024-04-23T18:35:56.13Z","@version":"1","message":"Resource not found path=/test-yoinakky/kafka-broker-mylhzxyo host=kafka-broker-ingress.knative-eventing.svc:8080 hostHeader=kafka-broker-ingress.knative-eventing.svc:8080","logger_name":"dev.knative.eventing.kafka.broker.receiver.impl.ReceiverVerticle","thread_name":"vert.x-eventloop-thread-4","level":"WARN","level_value":30000,"path":"/test-yoinakky/kafka-broker-mylhzxyo","host":"kafka-broker-ingress.knative-eventing.svc:8080","hostHeader":"kafka-broker-ingress.knative-eventing.svc:8080"}
> {"@timestamp":"2024-04-23T18:36:14.591Z","@version":"1","message":"[Producer clientId=producer-8] Error while fetching metadata with correlation id 18036 : {knative-broker-test-yoinakky-kafka-broker-dnxsanim=UNKNOWN_TOPIC_OR_PARTITION, knative-broker-test-yoinakky-kafka-broker-xifvszir=UNKNOWN_TOPIC_OR_PARTITION, knative-broker-test-yoinakky-kafka-broker-mylhzxyo=UNKNOWN_TOPIC_OR_PARTITION, knative-broker-test-yoinakky-kafka-broker-bkvnydki=UNKNOWN_TOPIC_OR_PARTITION, knative-broker-test-yoinakky-kafka-broker-vpjsvlol=UNKNOWN_TOPIC_OR_PARTITION, knative-broker-test-yoinakky-kafka-broker-ledflhkr=UNKNOWN_TOPIC_OR_PARTITION, knative-broker-test-yoinakky-kafka-broker-lkiqrpgt=UNKNOWN_TOPIC_OR_PARTITION}","logger_name":"org.apache.kafka.clients.NetworkClient","thread_name":"kafka-producer-network-thread | producer-8","level":"WARN","level_value":30000}
> ```
> 
> What I find weird about this is that there is a missing resource for `/test-yoinakky/kafka-broker-mylhzxyo`, but there is also an `UNKNOWN_TOPIC_OR_PARTITION` for the same resource. So, somehow the producer knows about it but can't fetch metadata, but there is no resource in the host mapping and path mapping

I believe this "Remove mappings only after closing the Producer" should do it https://github.com/knative-extensions/eventing-kafka-broker/pull/3852/commits/309c59d14ab7f11eba3c9cdfe9f0267a6745e441

**Comment by Cali0707** [comment]
From the [most recent reconciler-tests failure](https://storage.googleapis.com/knative-prow/pr-logs/pull/knative-extensions_eventing-kafka-broker/3852/reconciler-tests_eventing-kafka-broker_main/1783091263864573952/artifacts/new-logs/kafka-broker-receiver-76f696698d-rl2cn-kafka-broker-receiver-2024-04-24%2011:32:05.427433355%20+0000%20UTC%20m=+1.927927398.log) (in particular, from the point where the OIDC tests fail):
```
{"@timestamp":"2024-04-24T11:29:53.393Z","@version":"1","message":"Reconcile ingress diff diff=DiffResult{added=[], intersection=[72225bfb-78cb-43ad-8b17-4b3d02d46605], removed=[]} contractGeneration=2","logger_name":"dev.knative.eventing.kafka.broker.core.reconciler.impl.ResourcesReconcilerImpl","thread_name":"vert.x-eventloop-thread-3","level":"INFO","level_value":20000,"diff":{"added":[],"intersection":["72225bfb-78cb-43ad-8b17-4b3d02d46605"],"removed":[]},"contractGeneration":2}
{"@timestamp":"2024-04-24T11:29:53.4Z","@version":"1","message":"[Producer clientId=producer-1] Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms.","logger_name":"org.apache.kafka.clients.producer.KafkaProducer","thread_name":"","level":"INFO","level_value":20000}
{"@timestamp":"2024-04-24T11:29:53.4Z","@version":"1","message":"[Producer clientId=producer-2] Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms.","logger_name":"org.apache.kafka.clients.producer.KafkaProducer","thread_name":"","level":"INFO","level_value":20000}
{"@timestamp":"2024-04-24T11:29:53.4Z","@version":"1","message":"[Producer clientId=producer-3] Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms.","logger_name":"org.apache.kafka.clients.producer.KafkaProducer","thread_name":"","level":"INFO","level_value":20000}
{"@timestamp":"2024-04-24T11:29:53.403Z","@version":"1","message":"Failed to send record topic=knative-broker-sacura-broker {}","logger_name":"dev.knative.eventing.kafka.broker.receiver.impl.handler.IngressRequestHandlerImpl","thread_name":"vert.x-eventloop-thread-5","level":"ERROR","level_value":40000,"stack_trace":"io.vertx.core.impl.NoStackTraceThrowable: Producer is closed\n","topic":"knative-broker-sacura-broker"}
{"@timestamp":"2024-04-24T11:29:53.403Z","@version":"1","message":"[Producer clientId=producer-4] Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms.","logger_name":"org.apache.kafka.clients.producer.KafkaProducer","thread_name":"","level":"INFO","level_value":20000}
{"@timestamp":"2024-04-24T11:29:53.408Z","@version":"1","message":"Failed to produce record path=/sacura/broker","logger_name":"dev.knative.eventing.kafka.broker.receiver.impl.handler.IngressRequestHandlerImpl","thread_name":"vert.x-eventloop-thread-5","level":"WARN","level_value":30000,"stack_trace":"io.vertx.core.impl.NoStackTraceThrowable: Producer is closed\n","path":"/sacura/broker"}
{"@timestamp":"2024-04-24T11:29:53.414Z","@version":"1","message":"Metrics scheduler closed","logger_name":"org.apache.kafka.common.metrics.Metrics","thread_name":"","level":"INFO","level_value":20000}
{"@timestamp":"2024-04-24T11:29:53.415Z","@version":"1","message":"Closing reporter org.apache.kafka.common.metrics.JmxReporter","logger_name":"org.apache.kafka.common.metrics.Metrics","thread_name":"","level":"INFO","level_value":20000}
{"@timestamp":"2024-04-24T11:29:53.415Z","@version":"1","message":"Metrics reporters closed","logger_name":"org.apache.kafka.common.metrics.Metrics","thread_name":"","level":"INFO","level_value":20000}
{"@timestamp":"2024-04-24T11:29:53.416Z","@version":"1","message":"App info kafka.producer for producer-3 unregistered","logger_name":"org.apache.kafka.common.utils.AppInfoParser","thread_name":"","level":"INFO","level_value":20000}
{"@timestamp":"2024-04-24T11:29:53.417Z","@version":"1","message":"Metrics scheduler closed","logger_name":"org.apache.kafka.common.metrics.Metrics","thread_name":"","level":"INFO","level_value":20000}
{"@timestamp":"2024-04-24T11:29:53.418Z","@version":"1","message":"Closing reporter org.apache.kafka.common.metrics.JmxReporter","logger_name":"org.apache.kafka.common.metrics.Metrics","thread_name":"","level":"INFO","level_value":20000}
```

It looks like for some reason our producer gets closed, and then we try again to send to the producer

**Comment by Cali0707** [comment]
/test integration-tests
They passed...

**Comment by pierDipi** [comment]
/test integration-tests
They passed...

**Comment by pierDipi** [comment]
To make the OIDC test fail locally I'm running the test 10 times with parallel 42

```shell
BROKER_CLASS=Kafka SYSTEM_NAMESPACE=knative-eventing go test -timeout=1h -count=10 -v -tags=e2e -parallel=42 -run TestBrokerSendsEventsWithOIDCSupport ./test/e2e_new
```

and then on the failed test broker, I'm sending a request like this and getting 401 but I don't see any logs on the receiver side

```shell
kubectl run curl --image=curlimages/curl --rm=true --restart=Never -ti -- -k -X POST -v     -H "content-type: application/json"      -H "ce-specversion: 1.0"      -H "ce-source: my/curl/command"      -H "ce-type: my.demo.event"      -H "ce-id: 0816"   -H "Authorization: Bearer $(k create token -n test-huurmbef --audience "dls-audience" trigger-tjupkgaw-oidc-eventing.knative.dev-trigger)"   -d '{"name":"Hello"}'  https://kafka-broker-ingress.knative-eventing.svc.cluster.local/test-huurmbef/broker-ymuypdik
```

**Comment by pierDipi** [comment]
hmm
```
        	Error:      	Expected nil, but got: &errors.StatusError{ErrStatus:v1.Status{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ListMeta:v1.ListMeta{SelfLink:"", ResourceVersion:"", Continue:"", RemainingItemCount:(*int64)(nil)}, Status:"Failure", Message:"Unauthorized", Reason:"Unauthorized", Details:(*v1.StatusDetails)(nil), Code:401}}
```

**Comment by pierDipi** [comment]
```
    "message": "{\"kind\":\"Sent\",\"error\":\"Post \\\"https://kafka-sink-ingress.knative-eventing.svc.cluster.local/test-wglrrech/kafka-sink-zfvevgaz\\\": EOF\",\"origin\":\"eventshub-sender-ksrfyfyx\",\"observer\":\"eventshub-sender-ksrfyfyx\",\"time\":\"2024-04-29T14:27:04.411850719Z\",\"sequence\":1,\"id\":\"75fb7798-0591-479c-98f0-a9a36e7c2091\",\"additionalInfo\":null}",
```
/test reconciler-tests

**Comment by Cali0707** [comment]
Wooo all green :tada: :tada: 

@pierDipi should we think about merging some of these changes soon?

**Review by creydr — COMMENTED** [review]
/lgtm

/hold
to adjust the title

**Comment by creydr** [comment]
/hold cancel
as title is already adjusted

**Comment by creydr** [comment]
> @pierDipi: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> 
> Test name	Commit	Details	Required	Rerun command
> channel-reconciler-tests-sasl-ssl_eventing-kafka-broker_main	[d133f6b](https://github.com/knative-extensions/eventing-kafka-broker/commit/d133f6b08ab055b69a87417b789a004cdd2294bb)	[link](https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative-extensions_eventing-kafka-broker/3852/channel-reconciler-tests-sasl-ssl_eventing-kafka-broker_main/1785209803828629504)	true	`/test channel-reconciler-tests-sasl-ssl`
> reconciler-tests_eventing-kafka-broker_main	[d133f6b](https://github.com/knative-extensions/eventing-kafka-broker/commit/d133f6b08ab055b69a87417b789a004cdd2294bb)	[link](https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative-extensions_eventing-kafka-broker/3852/reconciler-tests_eventing-kafka-broker_main/1785197570478313472)	true	`/test reconciler-tests`
> [Your PR dashboard](https://prow.knative.dev/pr).

No logs :thinking: 

/retest-required

**Pull request merged**
