### PR TITLE
[release-1.13] Include TLS resources in release test setup

### PR DESCRIPTION
**Pull request by creydr**
Cherry-pick of #3636

### CODE REVIEW

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Comment by creydr** [comment]
@pierDipi @Cali0707 does the error in https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative-extensions_eventing-kafka-broker/3638/reconciler-tests_eventing-kafka-broker_release-1.13/1750867989730693120 with `TestKnativeKafkaCloudEventExtensionsAdded` ring any bells on you?

Is this a flake?

**Comment by Cali0707** [comment]
Hmm, looks like the kafka source didn't get set up properly? It might be a flake, not sure.

I added that test here: https://github.com/knative-extensions/eventing-kafka-broker/pull/3464

We can probably skip that test for now if it's flaky as we are already testing that stuff on broker + channel

**Comment by creydr** [comment]
@pierDipi @Cali0707 objections with overriding it?

**Comment by creydr** [comment]
/override reconciler-tests_eventing-kafka-broker_release-1.13

**Pull request merged**
