### PR TITLE
[release-1.11] Fix binary events with no data and ce overrides not being delivered (#3475)

### PR DESCRIPTION
**Pull request by Cali0707**
Manual cherry pick of https://github.com/knative-extensions/eventing-kafka-broker/pull/3475 with the build issues fixed

### CODE REVIEW

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Comment by Cali0707** [comment]
> sacura      broker         3m7s   False   cannot obtain Kafka cluster admin, kafka: client has run out of available brokers to talk to: dial tcp: lookup my-cluster-kafka-bootstrap.kafka on 10.60.0.10:53: no such host

**Comment by Cali0707** [comment]
Closing as 1.11 is no longer supported

**Pull request closed without merging**
