### PR TITLE
Add KafkaSource v1 API

### PR DESCRIPTION
**Pull request by pierDipi**
Part of https://github.com/knative-extensions/eventing-kafka-broker/issues/3953

## Proposed Changes

- [Add KafkaSource v1 types](https://github.com/knative-extensions/eventing-kafka-broker/commit/3ee8c9bfb6ce64871e08ef1bb199875986e71df2) (copy-paste v1beta1 and replace v1beta1 with v1)
- [Add conversions functions](https://github.com/knative-extensions/eventing-kafka-broker/commit/f51c244cea8f0d4364a6a3e0d4c0caf252ef67bd)
- [Update CRD resource](https://github.com/knative-extensions/eventing-kafka-broker/commit/fdf07eea7e4f048e4ee044ec469aeca6c7b880a7)
- [Add conversion webhook](https://github.com/knative-extensions/eventing-kafka-broker/commit/b110c484eb4aaba03ff6251e9b6dad79a5d4c5a4)

**Release Note**

```release-note
Add KafkaSource v1 API
```

**Docs**

### CODE REVIEW

**Comment by pierDipi** [comment]
Boilerplate errors, I think I will ignore them, too many files that are copy-pasted need to be changed

**Review by matzew — APPROVED** [review]
/lgtm
/approve

thanks for driving this, and yes lot's of copy-pasta here.

LGTM!

**Pull request merged**
