### PR TITLE
Fixed composite prober logic

### LINKED ISSUE #3262: Composite Prober causes finalizers to hang
**Describe the bug**
When used properly in a `FinalizeKind` function (see #3261 #3252) the tests fail as the resources are unable to be deleted.

 **Expected behavior**
When used in a finalizer, the resource should still be able to be deleted.

 **To Reproduce**
Use the composite prober in a `FinalizeKind` function which checks the prober status.

 **Knative release version**

 **Additional context**
Add any other context about the problem here such as proposed priority

### PR DESCRIPTION
**Pull request by Cali0707**
Fixes #3262

## Proposed Changes

- Fix the status accumulation logic

**Release Note**

```release-note
fixed the prober logic for addresses which could be http or https
```

### CODE REVIEW

**Comment by Cali0707** [comment]
This should fix the failing tests on #3267 #3261 and #3252

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
