### PR TITLE
Add KafkaSource reconciler test

### PR DESCRIPTION
**Pull request by pierDipi**
Part of #312

## Proposed Changes

- Add basic test for KafkaSource reconciler

### CODE REVIEW

**Comment by pierDipi** [comment]
This is based on https://github.com/knative-sandbox/eventing-kafka-broker/pull/1295
/hold

**Comment by aliok** [comment]
/lgtm
/approve
/hold

Feel free to unhold after #1295.

**Comment by matzew** [comment]
/lgtm
/approve

/hold
@pierDipi feel free to unhold

**Pull request merged**
