### PR TITLE
Remove unused vertx-kafka-client from dependencies

### PR DESCRIPTION
**Pull request by pierDipi**
As per title

### CODE REVIEW

**Review by creydr — APPROVED** [review]
/lgtm

**Comment by pierDipi** [comment]
```
   wait.go:200: test-zixonxhy/kafka-sink-xkznaluv condition is {"type":"Ready","status":"False","lastTransitionTime":"2024-05-07T11:01:44Z","reason":"Topic is not present or invalid","message":"topics [topic-levysyej]: invalid topic topic-levysyej"}
```

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
