### PR TITLE
Using the composite prober for the sink

### LINKED ISSUE #3189: Use the composite prober for the sink
**Problem**
Once https://github.com/knative-sandbox/eventing-kafka-broker/issues/3176 is complete, we should use the composite prober to probe the sink, instead of the async prober we are currently using. 

To do this, you will need to update the `Prober` type in the `Reconciler` struct from `Prober` to `NewProber` in https://github.com/knative-sandbox/eventing-kafka-broker/blob/main/control-plane/pkg/reconciler/sink/kafka_sink.go. Then, you will be able to do something similar to: https://github.com/knative-sandbox/eventing-kafka-broker/blob/main/control-plane/pkg/reconciler/broker/controller.go#L105 in https://github.com/knative-sandbox/eventing-kafka-broker/blob/main/control-plane/pkg/reconciler/sink/controller.go

You will also need to add code to handle rotating the CA certificates, which can be done similarly to https://github.com/knative-sandbox/eventing-kafka-broker/blob/59371d0edf02a4f42886c1ab333b9647085ac850/control-plane/pkg/reconciler/broker/controller.go#L127-L135 

Then, you must add/modify the appropriate event handler: https://github.com/knative-sandbox/eventing-kafka-broker/blob/59371d0edf02a4f42886c1ab333b9647085ac850/control-plane/pkg/reconciler/broker/controller.go#L152-L155

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**
The sink probes with the composite prober instead of the async prober, and resolves properly for all transport encryption flags.

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve? 1

**Additional context (optional)**
Add any other context about the feature request here.
- https://github.com/knative-sandbox/eventing-kafka-broker/pull/3178
- https://github.com/knative-sandbox/eventing-kafka-broker/issues/3141

### PR DESCRIPTION
**Pull request by Rahul-Kumar-prog**
Fixes #3189 

## Proposed Changes

- Update the Kafka_sink controller to use the prober with tls if the transport encryption flag is set to strict.

**Release Note**

```release-note
The Kafka_sink now uses a tls-enabled prober if the transport encryption flag is set to strict.
```

**Docs**

### CODE REVIEW

**Review by Cali0707 — APPROVED** [review]
/lgtm

**Comment by Rahul-Kumar-prog** [comment]
Hey @Cali0707 what is the status of this issue ??

**Review by pierDipi — APPROVED** [review]
Thanks @Rahul-Kumar-prog and @Cali0707, well done!

/approve

**Pull request merged**
