### PR TITLE
Add version tag for maven plugin(#3551)

### LINKED ISSUE #3551: Fix maven build warning for missing plugin version
**Describe the bug**
Currently, when building the data plane, we get the following warning:
```
WARNING] 
[WARNING] Some problems were encountered while building the effective model for dev.knative.eventing.kafka.broker:core:jar:1.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-jar-plugin is missing. @ line 219, column 15
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for dev.knative.eventing.kafka.broker:receiver:jar:1.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-jar-plugin is missing. @ line 75, column 15
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for dev.knative.eventing.kafka.broker:dispatcher:jar:1.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-jar-plugin is missing. @ line 93, column 15
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
```

We should specify the version for `org.apache.maven.plugins:maven-jar-plugin` in the three places mentioned in these logs. It looks like 3.3.0 is the newest version.

 **Expected behavior**
This warning is not present when building the data plane.

 **To Reproduce**
Run any script which builds the data plane. For example, run `./hack/run.sh unit-tests-data-plane`

 **Knative release version**
release-next

 **Additional context**
Add any other context about the problem here such as proposed priority

### PR DESCRIPTION
**Pull request by shikharish**
Closes #3551.

### CODE REVIEW

**Comment by Cali0707** [comment]
Hi @shikharish can you fill out the CLA? You should be able to complete it by just clicking on the link in the comment from the CLA bit and following the instructions there.

**Comment by shikharish** [comment]
> Hi @shikharish can you fill out the CLA? You should be able to complete it by just clicking on the link in the comment from the CLA bit and following the instructions there.

Done!

**Comment by Cali0707** [comment]
@shikharish the failing tests are likely unrelated to this change, as we have flaky CI in this repo
/retest-required

**Comment by shikharish** [comment]
@Cali0707 Can that failing test be due to my change? Any way for me to debug it?

**Comment by Cali0707** [comment]
@shikharish these failures likely aren’t related, just needs another round of testing. 

/test reconciler-tests-namespaced-broker

**Review by Cali0707 — APPROVED** [review]
/lgtm
/approve

Thanks @shikharish, welcome to Knative! If you want to keep contributing to the project, feel free to check out the other issues with "good first issue" or "help wanted" labels, and to join the #knative-* channels on the CNCF slack. We'd love to see you there!

**Comment by shikharish** [comment]
Thank you very much!

**Pull request merged**
