### PR TITLE
[WIP] Fix the flaky FileWatcher unit test in the data plane

### LINKED ISSUE #3536: Fix the flaky FileWatcher unit test in the data plane
**Describe the bug**
With the bump to JDK 21, the `FileWatcherTest` test fails in Github Actions but passes in Prow (and often locally). 

 **Expected behavior**
The test should consistently pass

 **To Reproduce**
Run the `FileWatcherTest` tests in Github Actions

 **Knative release version**
main

 **Additional context**

The error logs from the tests are:
```
[INFO] 
[INFO] Results:
[INFO] 
Error:  Errors: 
Error:    FileWatcherTest.testFileModification:64 » ConditionTimeout Condition dev.knative.eventing.kafka.broker.core.file.FileWatcherTest$$Lambda/0x00007f011417fa10 was not fulfilled within 10 seconds.
```

### PR DESCRIPTION
**Pull request by Leo6Leo**
Fixes #3536

## Proposed Changes

- WIP, currently in the investigating stage
-
-

**Release Note**

```release-note

```

**Docs**

### CODE REVIEW

**Comment by Leo6Leo** [comment]
I have run few times on GitHub action and locally, the fileWatcher test didn't fail at all. 

/cc @matzew @Cali0707

**Review by pierDipi — COMMENTED** [review]
@Leo6Leo is this still WIP ?

**Comment by Leo6Leo** [comment]
@pierDipi  I used this PR as a test to see how flaky that test is on GitHub Action. But it seems like it didn't fail at all. So I think it should be good to close it after @matzew see this.

**Comment by Leo6Leo** [comment]
The dependency upgrade tests are passing on GitHub as shown [here](https://github.com/knative-extensions/eventing-kafka-broker/actions/workflows/knative-java-test.yaml?query=branch%3Amain+event%3Apush), so closing this issue.

**Pull request closed without merging**
