### PR TITLE
Add Code formatting check post Pull-Request (#3349)

### LINKED ISSUE #3349: Spotless is not verified on PRs
**Describe the bug**
It seems like the code is not being verified to match the formatting provided by Spotless on PRs, as subsequent PRs are reformatting the code when `./hack/update-codegen.sh` is run.

 **Expected behavior**
If code is not formatted properly, some CI job fails and indicates that the code should be formatted.

 **To Reproduce**
Create a PR with Java code and don't run the Spotless format command.

 **Knative release version**

 **Additional context**
Add any other context about the problem here such as proposed priority

### PR DESCRIPTION
**Pull request by prakhar479**
* Bug: added code formatting check in java test pull request hook
Signed-off-by: Prakhar Singhal <153047595+prakhar479@users.noreply.github.com>

Fixes #
- 🧹 Fixes #3349

### CODE REVIEW

**Comment by prakhar479** [comment]
seems like the java tests are failing. I found following as first point of failure:
```
Running dev.knative.eventing.kafka.broker.core.file.FileWatcherTest
```
with error:
```
Error:  Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 10.68 s <<< FAILURE! -- in dev.knative.eventing.kafka.broker.core.file.FileWatcherTest
```

these were some relevant logs between initialization and error:
```
09:06:16.244 [contract-file-watcher] INFO  dev.knative.eventing.kafka.broker.core.file.FileWatcher - Started watching /tmp/test5718446383111542373.txt
09:06:16.267 [contract-file-watcher] DEBUG dev.knative.eventing.kafka.broker.core.file.FileWatcher - Contract updates
09:06:16.284 [contract-file-watcher] DEBUG dev.knative.eventing.kafka.broker.core.file.FileWatcher - Contract updates
09:06:26.325 [contract-file-watcher] INFO  dev.knative.eventing.kafka.broker.core.file.FileWatcher - Started watching /tmp/test654706480592262681.txt
```

Can someone help with following since I did not make any changes to core logic and thus am unsure why are these failing. thanks!

**Comment by Leo6Leo** [comment]
emm, this flaky test appears again. That's a separate issue, and this is not related to your PR @prakhar479 . 

I will look into this and get back to you, thanks for providing the clear description of the error logs!

**Comment by pierDipi** [comment]
Fix for the flaky test is here #4029

**Comment by prakhar479** [comment]
@Leo6Leo I have re-ran all tests. we are ready to proceed with the rest of merge process. Thanks!

**Review by Cali0707 — COMMENTED** [review]
Thanks for starting on this @prakhar479 !

Could you also add this to  https://github.com/knative-extensions/eventing-kafka-broker/blob/dcb704a237966c59459e12d6a7095f637e3e8243/test/presubmit-tests.sh#L35-L38 so that it gets verifies by the blocking test jobs as well as the non-blocking Java unit test you've added it to so far?

**Comment by prakhar479** [comment]
> Thanks for starting on this @prakhar479 !
> 
> Could you also add this to
> 
> https://github.com/knative-extensions/eventing-kafka-broker/blob/dcb704a237966c59459e12d6a7095f637e3e8243/test/presubmit-tests.sh#L35-L38
> 
> so that it gets verifies by the blocking test jobs as well as the non-blocking Java unit test you've added it to so far?

I have added the formatting check for control plane as well. thanks!

**Comment by prakhar479** [comment]
I am not quite able to understand why the `reconciler-tests` are failing. Following error in `TestKafkaChannelOIDC/KafkaChannel_handles_requests_with_OIDC_tokens_correctly/KafkaChannel_reject_event_for_wrong_OIDC_audience/Assert/KafkaChannel_get_401_on_response ` denotes a internal error:
```
- Match errors -
        0 - event status code don't match. Expected: '401', Actual: '0'
        1 - event status code don't match. Expected: '401', Actual: '0'
        2 - event status code don't match. Expected: '401', Actual: '0'
        3 - event status code don't match. Expected: '401', Actual: '500'
```
and both failed processes return with code `255`. I am not quite sure what causes the error. What am I missing @pierDipi @Leo6Leo @Cali0707 ?

**Pull request closed without merging**
