### PR TITLE
Bump CloudEvents GO-SDK to 2.15.2

### PR DESCRIPTION
**Pull request by matzew**
## Proposed Changes

- lastest of Go-Sdk

**Release Note**

```release-note
Using 2.15.2 of Go-sdk for CloudEvents
```

**Docs**

### CODE REVIEW

**Comment by matzew** [comment]
This replaces :  https://github.com/knative-extensions/eventing-kafka-broker/pull/3737

**Review by aliok — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
