### PR TITLE
Updating data plane to Quarkus 3.8.x

### PR DESCRIPTION
**Pull request by matzew**
Fixes #

## Proposed Changes

- bump to next Quarkus version
- align vertx
- align jackson
- newer kafka

**Release Note**

```release-note

```

**Docs**

### CODE REVIEW

**Review by creydr — APPROVED** [review]
/lgtm

**Comment by matzew** [comment]
/retest
as always LOL

**Comment by creydr** [comment]
A bit strange that the same tests keep failing over and over again :thinking:

**Comment by creydr** [comment]
> @matzew: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

As we have other PRs going in to main (e.g. #3728) and we see the same test failing consistently here, I think there is something wrong with this bump :/

**Review by creydr — COMMENTED** [review]
/lgtm

**Comment by creydr** [comment]
On the [reconciler tests](https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative-extensions_eventing-kafka-broker/3714/reconciler-tests_eventing-kafka-broker_main/1767228728800186368), I see `TestTracingHeaders/TracingHeadersUsingOrderedDeliveryWithTraceExported` failing consistently.
Same for the `TestChannelTracing/eventWithTraceExported` test in the channel reconciler tests.

So I guess something changed there in quarkus related to tracing...

**Comment by matzew** [comment]
/close
b/c of 3856

**Pull request closed without merging**
