### PR TITLE
 [main] Upgrade to latest dependencies

### PR DESCRIPTION
**Pull request by creydr**
Same as #4152, but also removes the scheduler config to align with https://github.com/knative/eventing/pull/8263

### CODE REVIEW

**Review by Cali0707 — APPROVED** [review]
/lgtm

Thanks for fixing the update @creydr !

**Comment by creydr** [comment]
```
Error: init failed to get project from boskos: failed to get a "gke-project" from boskos: resources not found
```
/retest

**Comment by creydr** [comment]
```
Error: init failed to get project from boskos: failed to get a "gke-project" from boskos: resources not found
```
trying again
/retest

**Comment by creydr** [comment]
https://cloud-native.slack.com/archives/C04LY4M2G49/p1732698491524499
/retest

**Comment by pierDipi** [comment]
I had also https://github.com/knative-extensions/eventing-kafka-broker/pull/4149 but it's failing sacura tests

**Comment by creydr** [comment]
Closing in favor of https://github.com/knative-extensions/eventing-kafka-broker/pull/4149

**Pull request closed without merging**
