### PR TITLE
Pass event type owner references to the data plane

### PR DESCRIPTION
**Pull request by Cali0707**
With the contract now including fields to ET owner references (needed for autocreate), we should pass those values to the data plane.

## Proposed Changes

- Pass the owner reference info to the data plane.

### CODE REVIEW

**Comment by Cali0707** [comment]
Oh - just realized we probably want to backport the data plane contract fix before the upgrade tests will start to pass. I'll open a PR on Monday for that.

**Review by creydr — APPROVED** [review]
/lgtm

**Pull request merged**
