### PR TITLE
Align to the defaults, list all - for convenience

### PR DESCRIPTION
**Pull request by matzew**
## Proposed Changes

- adding missing features to have a "complete" feature list, to easily switch _all_ existing features

**Release Note**

```release-note

```

**Docs**

### CODE REVIEW

**Review by creydr — APPROVED** [review]
nit: order different as in https://github.com/knative-extensions/eventing-kafka-broker/blob/e0d1f198d2cedcaaf23119a16f1a852d6fb507a9/test/config-transport-encryption/features.yaml but LGTM

/lgtm

/hold
in case you want to have the same ordering

**Comment by matzew** [comment]
@creydr it's the same order as upstream: https://github.com/knative/eventing/blob/main/config/core/configmaps/features.yaml

That's why 

/unhold

**Pull request merged**
