### PR TITLE
adding s390x and ppc64le platform for loom based builds

### PR DESCRIPTION
**Pull request by dilipgb**
Fixes #
#3776 

## Proposed Changes
This PR enables the Docker image build for the dataplane components receiver-loom and dispatcher-loom for the s390x and ppc64le architecture. For this it leverages jib's multi-arch Docker image build capabilities.

### CODE REVIEW

**Comment by dilipgb** [comment]
@matzew can you please take a look at this PR. This PR will add dispatcher-loom and receiver-loom builds for s390x and ppc64le architecture.

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
