### PR TITLE
[release-1.12] Cherry-pick E2E tests for channel: TLS key pair rotation #3406

### PR DESCRIPTION
**Pull request by Leo6Leo**
Cherry-pick https://github.com/knative-extensions/eventing-kafka-broker/pull/3406/files

### CODE REVIEW

**Comment by Leo6Leo** [comment]
Github action is using java 20, and prow is using java 21

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Comment by Cali0707** [comment]
Hey @pierDipi @Leo6Leo can we unhold this PR now?

**Pull request merged**
