### PR TITLE
Upgrade tests install eventing core from release

### PR DESCRIPTION
**Pull request by Cali0707**
Currently, the scripts we use to install eventing and eventing kafka broker components in the upgrade tests do not install a previous release of eventing when installing the previous release of eventing kafka broker. This can cause some test failures due to incompatible versioning.

## Proposed Changes

- Install the previous eventing release along with the previous eventing kafka broker release
- Install the latest eventing nightly when upgrading to the newer eventing kafka broker code

### CODE REVIEW

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Comment by creydr** [comment]
```
=== FAIL: test/upgrade TestUpgrades/Run/Steps/UpgradeWith/GitHead (37.35s)
    executor.go:189: Apr 22 19:41:34.099 install_eventing_core [OUT] Updating release labels to app.kubernetes.io/version: "47de523d5fbe963e4d155f6293ba963593d5ff3a"
    ...
    executor.go:189: Apr 22 19:41:41.660 install_eventing_core [OUT] configmap/config-sugar configured
    executor.go:189: Apr 22 19:41:41.714 install_eventing_core [ERR] Warning: resource configmaps/config-tracing is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
    ...
    executor.go:189: Apr 22 19:41:53.196 install_eventing_core [OUT] certificate.cert-manager.io/mt-broker-ingress-server-tls unchanged
    executor.go:189: Apr 22 19:41:53.560 install_eventing_core [OUT] horizontalpodautoscaler.autoscaling/eventing-webhook patched
    shell.go:30: exit status 1
```

**Comment by creydr** [comment]
cluster didn't come up...

/test upgrade-tests

**Comment by Cali0707** [comment]
```
executor.go:189: Apr 23 13:13:54.639 install_eventing_core [OUT] Updating release labels to app.kubernetes.io/version: "1cd4a06c9a92e32e18e8f73fb3870327bcf510ba"
    executor.go:189: Apr 23 13:13:54.639 install_eventing_core [OUT] Using loom modules true
    executor.go:189: Apr 23 13:13:54.643 install_eventing_core [OUT] Updating release labels to app.kubernetes.io/version: "1cd4a06c9a92e32e18e8f73fb3870327bcf510ba"
    executor.go:189: Apr 23 13:13:54.659 install_eventing_core [OUT] >> Install Knative Eventing from latest - ./third_party/eventing-latest/
    executor.go:189: Apr 23 13:13:55.182 install_eventing_core [OUT] customresourcedefinition.apiextensions.k8s.io/apiserversources.sources.knative.dev configured
    executor.go:189: Apr 23 13:13:55.338 install_eventing_core [OUT] customresourcedefinition.apiextensions.k8s.io/brokers.eventing.knative.dev configured
    executor.go:189: Apr 23 13:13:55.510 install_eventing_core [OUT] customresourcedefinition.apiextensions.k8s.io/channels.messaging.knative.dev configured
    executor.go:189: Apr 23 13:13:55.646 install_eventing_core [OUT] customresourcedefinition.apiextensions.k8s.io/containersources.sources.knative.dev configured
    executor.go:189: Apr 23 13:13:55.800 install_eventing_core [OUT] customresourcedefinition.apiextensions.k8s.io/eventtypes.eventing.knative.dev configured
    executor.go:189: Apr 23 13:13:55.971 install_eventing_core [OUT] customresourcedefinition.apiextensions.k8s.io/parallels.flows.knative.dev configured
    executor.go:189: Apr 23 13:13:56.168 install_eventing_core [OUT] customresourcedefinition.apiextensions.k8s.io/pingsources.sources.knative.dev configured
    executor.go:189: Apr 23 13:13:56.325 install_eventing_core [OUT] customresourcedefinition.apiextensions.k8s.io/sequences.flows.knative.dev configured
    executor.go:189: Apr 23 13:13:56.455 install_eventing_core [OUT] customresourcedefinition.apiextensions.k8s.io/sinkbindings.sources.knative.dev configured
    executor.go:189: Apr 23 13:13:56.608 install_eventing_core [OUT] customresourcedefinition.apiextensions.k8s.io/subscriptions.messaging.knative.dev configured
    executor.go:189: Apr 23 13:13:56.752 install_eventing_core [OUT] customresourcedefinition.apiextensions.k8s.io/triggers.eventing.knative.dev configured
    executor.go:189: Apr 23 13:13:58.413 install_eventing_core [OUT] namespace/knative-eventing configured
    executor.go:189: Apr 23 13:13:58.608 install_eventing_core [OUT] serviceaccount/eventing-controller configured
    executor.go:189: Apr 23 13:13:58.734 install_eventing_core [OUT] clusterrolebinding.rbac.authorization.k8s.io/eventing-controller configured
    executor.go:189: Apr 23 13:13:58.875 install_eventing_core [OUT] clusterrolebinding.rbac.authorization.k8s.io/eventing-controller-resolver configured
    executor.go:189: Apr 23 13:13:59.016 install_eventing_core [OUT] clusterrolebinding.rbac.authorization.k8s.io/eventing-controller-source-observer configured
    executor.go:189: Apr 23 13:13:59.165 install_eventing_core [OUT] clusterrolebinding.rbac.authorization.k8s.io/eventing-controller-sources-controller configured
    executor.go:189: Apr 23 13:13:59.311 install_eventing_core [OUT] clusterrolebinding.rbac.authorization.k8s.io/eventing-controller-manipulator configured
    executor.go:189: Apr 23 13:13:59.508 install_eventing_core [OUT] serviceaccount/pingsource-mt-adapter configured
    executor.go:189: Apr 23 13:13:59.648 install_eventing_core [OUT] clusterrolebinding.rbac.authorization.k8s.io/knative-eventing-pingsource-mt-adapter configured
    executor.go:189: Apr 23 13:13:59.839 install_eventing_core [OUT] serviceaccount/eventing-webhook configured
    executor.go:189: Apr 23 13:13:59.980 install_eventing_core [OUT] clusterrolebinding.rbac.authorization.k8s.io/eventing-webhook configured
    executor.go:189: Apr 23 13:14:00.128 install_eventing_core [OUT] rolebinding.rbac.authorization.k8s.io/eventing-webhook configured
    executor.go:189: Apr 23 13:14:00.249 install_eventing_core [OUT] clusterrolebinding.rbac.authorization.k8s.io/eventing-webhook-resolver configured
    executor.go:189: Apr 23 13:14:00.408 install_eventing_core [OUT] clusterrolebinding.rbac.authorization.k8s.io/eventing-webhook-podspecable-binding configured
    executor.go:189: Apr 23 13:14:00.461 install_eventing_core [ERR] Warning: resource configmaps/config-br-default-channel is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
    executor.go:189: Apr 23 13:14:00.612 install_eventing_core [OUT] configmap/config-br-default-channel configured
    executor.go:189: Apr 23 13:14:00.810 install_eventing_core [OUT] configmap/config-br-defaults configured
    executor.go:189: Apr 23 13:14:00.996 install_eventing_core [OUT] configmap/default-ch-webhook configured
    executor.go:189: Apr 23 13:14:01.193 install_eventing_core [OUT] configmap/config-ping-defaults configured
    executor.go:189: Apr 23 13:14:01.372 install_eventing_core [OUT] configmap/config-features configured
    executor.go:189: Apr 23 13:14:01.540 install_eventing_core [OUT] configmap/config-kreference-mapping unchanged
    executor.go:189: Apr 23 13:14:01.767 install_eventing_core [OUT] configmap/config-leader-election configured
    executor.go:189: Apr 23 13:14:01.967 install_eventing_core [OUT] configmap/config-logging configured
    executor.go:189: Apr 23 13:14:02.163 install_eventing_core [OUT] configmap/config-observability configured
    executor.go:189: Apr 23 13:14:02.375 install_eventing_core [OUT] configmap/config-sugar configured
    executor.go:189: Apr 23 13:14:02.545 install_eventing_core [OUT] configmap/config-tracing configured
    executor.go:189: Apr 23 13:14:02.709 install_eventing_core [OUT] deployment.apps/eventing-controller configured
    executor.go:189: Apr 23 13:14:02.889 install_eventing_core [OUT] deployment.apps/pingsource-mt-adapter configured
    executor.go:189: Apr 23 13:14:03.017 install_eventing_core [OUT] horizontalpodautoscaler.autoscaling/eventing-webhook configured
    executor.go:189: Apr 23 13:14:03.289 install_eventing_core [OUT] poddisruptionbudget.policy/eventing-webhook configured
    executor.go:189: Apr 23 13:14:03.453 install_eventing_core [OUT] deployment.apps/eventing-webhook configured
    executor.go:189: Apr 23 13:14:03.697 install_eventing_core [OUT] service/eventing-webhook configured
    executor.go:189: Apr 23 13:14:03.864 install_eventing_core [OUT] customresourcedefinition.apiextensions.k8s.io/apiserversources.sources.knative.dev configured
    executor.go:189: Apr 23 13:14:03.924 install_eventing_core [OUT] customresourcedefinition.apiextensions.k8s.io/brokers.eventing.knative.dev unchanged
    executor.go:189: Apr 23 13:14:03.991 install_eventing_core [OUT] customresourcedefinition.apiextensions.k8s.io/channels.messaging.knative.dev unchanged
    executor.go:189: Apr 23 13:14:04.042 install_eventing_core [OUT] customresourcedefinition.apiextensions.k8s.io/containersources.sources.knative.dev unchanged
    executor.go:189: Apr 23 13:14:04.092 install_eventing_core [OUT] customresourcedefinition.apiextensions.k8s.io/eventtypes.eventing.knative.dev unchanged
    executor.go:189: Apr 23 13:14:04.192 install_eventing_core [OUT] customresourcedefinition.apiextensions.k8s.io/parallels.flows.knative.dev unchanged
    executor.go:189: Apr 23 13:14:04.263 install_eventing_core [OUT] customresourcedefinition.apiextensions.k8s.io/pingsources.sources.knative.dev unchanged
    executor.go:189: Apr 23 13:14:04.426 install_eventing_core [OUT] customresourcedefinition.apiextensions.k8s.io/sequences.flows.knative.dev unchanged
    executor.go:189: Apr 23 13:14:04.533 install_eventing_core [OUT] customresourcedefinition.apiextensions.k8s.io/sinkbindings.sources.knative.dev unchanged
    executor.go:189: Apr 23 13:14:04.640 install_eventing_core [OUT] customresourcedefinition.apiextensions.k8s.io/subscriptions.messaging.knative.dev unchanged
    executor.go:189: Apr 23 13:14:04.727 install_eventing_core [OUT] customresourcedefinition.apiextensions.k8s.io/triggers.eventing.knative.dev unchanged
    executor.go:189: Apr 23 13:14:04.911 install_eventing_core [OUT] clusterrole.rbac.authorization.k8s.io/addressable-resolver configured
    executor.go:189: Apr 23 13:14:05.056 install_eventing_core [OUT] clusterrole.rbac.authorization.k8s.io/service-addressable-resolver configured
    executor.go:189: Apr 23 13:14:05.217 install_eventing_core [OUT] clusterrole.rbac.authorization.k8s.io/serving-addressable-resolver configured
    executor.go:189: Apr 23 13:14:05.358 install_eventing_core [OUT] clusterrole.rbac.authorization.k8s.io/channel-addressable-resolver configured
    executor.go:189: Apr 23 13:14:05.526 install_eventing_core [OUT] clusterrole.rbac.authorization.k8s.io/broker-addressable-resolver configured
    executor.go:189: Apr 23 13:14:05.659 install_eventing_core [OUT] clusterrole.rbac.authorization.k8s.io/flows-addressable-resolver configured
    executor.go:189: Apr 23 13:14:05.809 install_eventing_core [OUT] clusterrole.rbac.authorization.k8s.io/eventing-broker-filter configured
    executor.go:189: Apr 23 13:14:05.953 install_eventing_core [OUT] clusterrole.rbac.authorization.k8s.io/eventing-broker-ingress configured
    executor.go:189: Apr 23 13:14:06.108 install_eventing_core [OUT] clusterrole.rbac.authorization.k8s.io/eventing-config-reader configured
    executor.go:189: Apr 23 13:14:06.258 install_eventing_core [OUT] clusterrole.rbac.authorization.k8s.io/channelable-manipulator configured
    executor.go:189: Apr 23 13:14:06.417 install_eventing_core [OUT] clusterrole.rbac.authorization.k8s.io/meta-channelable-manipulator configured
    executor.go:189: Apr 23 13:14:06.566 install_eventing_core [OUT] clusterrole.rbac.authorization.k8s.io/knative-eventing-namespaced-admin configured
    executor.go:189: Apr 23 13:14:06.720 install_eventing_core [OUT] clusterrole.rbac.authorization.k8s.io/knative-messaging-namespaced-admin configured
    executor.go:189: Apr 23 13:14:06.866 install_eventing_core [OUT] clusterrole.rbac.authorization.k8s.io/knative-flows-namespaced-admin configured
    executor.go:189: Apr 23 13:14:07.023 install_eventing_core [OUT] clusterrole.rbac.authorization.k8s.io/knative-sources-namespaced-admin configured
    executor.go:189: Apr 23 13:14:07.228 install_eventing_core [OUT] clusterrole.rbac.authorization.k8s.io/knative-bindings-namespaced-admin configured
    executor.go:189: Apr 23 13:14:07.388 install_eventing_core [OUT] clusterrole.rbac.authorization.k8s.io/knative-eventing-namespaced-edit configured
    executor.go:189: Apr 23 13:14:07.538 install_eventing_core [OUT] clusterrole.rbac.authorization.k8s.io/knative-eventing-namespaced-view configured
    executor.go:189: Apr 23 13:14:07.702 install_eventing_core [OUT] clusterrole.rbac.authorization.k8s.io/knative-eventing-controller configured
    executor.go:189: Apr 23 13:14:07.841 install_eventing_core [OUT] clusterrole.rbac.authorization.k8s.io/knative-eventing-pingsource-mt-adapter configured
    executor.go:189: Apr 23 13:14:07.989 install_eventing_core [OUT] clusterrole.rbac.authorization.k8s.io/podspecable-binding configured
    executor.go:189: Apr 23 13:14:08.129 install_eventing_core [OUT] clusterrole.rbac.authorization.k8s.io/builtin-podspecable-binding configured
    executor.go:189: Apr 23 13:14:08.269 install_eventing_core [OUT] clusterrole.rbac.authorization.k8s.io/source-observer configured
    executor.go:189: Apr 23 13:14:08.417 install_eventing_core [OUT] clusterrole.rbac.authorization.k8s.io/eventing-sources-source-observer configured
    executor.go:189: Apr 23 13:14:08.564 install_eventing_core [OUT] clusterrole.rbac.authorization.k8s.io/knative-eventing-sources-controller configured
    executor.go:189: Apr 23 13:14:08.720 install_eventing_core [OUT] clusterrole.rbac.authorization.k8s.io/knative-eventing-webhook configured
    executor.go:189: Apr 23 13:14:08.851 install_eventing_core [OUT] role.rbac.authorization.k8s.io/knative-eventing-webhook configured
    executor.go:189: Apr 23 13:14:08.982 install_eventing_core [OUT] validatingwebhookconfiguration.admissionregistration.k8s.io/config.webhook.eventing.knative.dev configured
    executor.go:189: Apr 23 13:14:09.119 install_eventing_core [OUT] mutatingwebhookconfiguration.admissionregistration.k8s.io/webhook.eventing.knative.dev configured
    executor.go:189: Apr 23 13:14:09.245 install_eventing_core [OUT] validatingwebhookconfiguration.admissionregistration.k8s.io/validation.webhook.eventing.knative.dev configured
    executor.go:189: Apr 23 13:14:09.450 install_eventing_core [OUT] secret/eventing-webhook-certs configured
    executor.go:189: Apr 23 13:14:09.580 install_eventing_core [OUT] mutatingwebhookconfiguration.admissionregistration.k8s.io/sinkbindings.webhook.sources.knative.dev configured
    executor.go:189: Apr 23 13:14:13.355 install_eventing_core [OUT] clusterissuer.cert-manager.io/knative-eventing-ca-issuer unchanged
    executor.go:189: Apr 23 13:14:13.421 install_eventing_core [OUT] clusterissuer.cert-manager.io/knative-eventing-selfsigned-issuer unchanged
    executor.go:189: Apr 23 13:14:13.487 install_eventing_core [OUT] certificate.cert-manager.io/knative-eventing-selfsigned-ca unchanged
    executor.go:189: Apr 23 13:14:13.662 install_eventing_core [OUT] configmap/knative-eventing-bundle unchanged
    executor.go:189: Apr 23 13:14:13.725 install_eventing_core [OUT] bundle.trust.cert-manager.io/knative-eventing-bundle unchanged
    executor.go:189: Apr 23 13:14:13.791 install_eventing_core [OUT] certificate.cert-manager.io/imc-dispatcher-server-tls unchanged
    executor.go:189: Apr 23 13:14:13.858 install_eventing_core [OUT] certificate.cert-manager.io/mt-broker-filter-server-tls unchanged
    executor.go:189: Apr 23 13:14:13.933 install_eventing_core [OUT] certificate.cert-manager.io/mt-broker-ingress-server-tls unchanged
    executor.go:189: Apr 23 13:14:14.199 install_eventing_core [OUT] horizontalpodautoscaler.autoscaling/eventing-webhook patched
    shell.go:30: exit status 1
```

Huh weird, I can't see anything that I think would cause the script to exit with status 1. There's just the one warning. @creydr any ideas?

**Comment by creydr** [comment]
> ```
>      ...
>     executor.go:189: Apr 23 13:14:14.199 install_eventing_core [OUT] horizontalpodautoscaler.autoscaling/eventing-webhook patched
>     shell.go:30: exit status 1
> ```
> 
> Huh weird, I can't see anything that I think would cause the script to exit with status 1. There's just the one warning. @creydr any ideas?

I was wondering the same in https://github.com/knative-extensions/eventing-kafka-broker/pull/3849#issuecomment-2071624003. Looking at https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative-extensions_eventing-kafka-broker/3829/upgrade-tests_eventing-kafka-broker_main/1782708091888865280 (from another PR where the upgrade tests passed), I think the `[ERR]` is a red herring. 
I'll continue with checking...

**Comment by creydr** [comment]
`unable to read URL "https://github.com/knative-extensions/eventing-kafka-broker/releases/download/knative-v1.13.8/eventing-kafka-sink.yaml", server reported 500 Internal Server Error, status code=500`

/test upgrade-tests

**Pull request merged**
