### PR TITLE
fix: go version in go mod is correct now

### PR DESCRIPTION
**Pull request by Cali0707**
Fixes issues with `go mod tidy` resulting from an incorrect go mod file. See https://github.com/golang/go/issues/62278#issuecomment-1693538776 for more info

## Proposed Changes

- Move from `go 1.22` to explicit `go 1.22.3`

### CODE REVIEW

**Comment by creydr** [comment]
Hey @Cali0707,
thanks for checking on this. Do you know, if this value will then be updated over time, or do we have to bump it manually?

**Comment by Cali0707** [comment]
>  Do you know, if this value will then be updated over time, or do we have to bump it manually?

Not sure, but I imagine we will have to bump this ourselves sadly...

**Comment by creydr** [comment]
> Not sure, but I imagine we will have to bump this ourselves sadly...

Ok. IIRC we had to do this in the past anyhow (for minor versions)

/lgtm

**Pull request merged**
