### PR TITLE
Upgrade to latest dependencies

### PR DESCRIPTION
**Pull request by creydr**
#3318 has some build issues. This PR addresses it

### CODE REVIEW

**Comment by creydr** [comment]
Has some other issues too:

```
Error from server (BadRequest): container "kafka-source-dispatcher" in pod "kafka-source-dispatcher-0" is waiting to start: ContainerCreating
```

we see the following event assigned to the pod:

```
kind: Event
  ...
  note: 'MountVolume.SetUp failed for volume "contract-resources" : configmap "kafka-source-dispatcher-0"
    not found'
  reason: FailedMount
  regarding:
    apiVersion: v1
    kind: Pod
    name: kafka-source-dispatcher-0
    namespace: knative-eventing
  type: Warning
```

But no configmap with this name:

```
>>> configmaps (63 objects)
>>> Listing
NAMESPACE          NAME                                                   DATA   AGE
...
knative-eventing   config-br-default-channel                              1      13m
knative-eventing   config-br-defaults                                     1      13m
knative-eventing   config-features                                        7      13m
knative-eventing   config-kafka-autoscaler                                7      5m31s
knative-eventing   config-kafka-broker-data-plane                         5      5m27s
knative-eventing   config-kafka-channel-data-plane                        5      5m24s
knative-eventing   config-kafka-descheduler                               2      5m31s
knative-eventing   config-kafka-features                                  6      5m31s
knative-eventing   config-kafka-leader-election                           6      5m31s
knative-eventing   config-kafka-scheduler                                 2      5m31s
knative-eventing   config-kafka-sink-data-plane                           3      5m26s
knative-eventing   config-kafka-source-data-plane                         4      5m28s
knative-eventing   config-kafka-source-defaults                           1      5m31s
knative-eventing   config-kreference-mapping                              1      13m
knative-eventing   config-leader-election                                 1      13m
knative-eventing   config-logging                                         3      13m
knative-eventing   config-namespaced-broker-resources                     1      5m31s
knative-eventing   config-observability                                   1      13m
knative-eventing   config-ping-defaults                                   1      13m
knative-eventing   config-sugar                                           1      13m
knative-eventing   config-tracing                                         4      13m
knative-eventing   default-ch-webhook                                     1      13m
knative-eventing   kafka-broker-brokers-triggers                          1      5m28s
knative-eventing   kafka-broker-config                                    3      5m32s
knative-eventing   kafka-channel-channels-subscriptions                   1      5m27s
knative-eventing   kafka-channel-config                                   1      5m31s
knative-eventing   kafka-config-logging                                   1      5m31s
knative-eventing   kafka-sink-sinks                                       1      5m27s
knative-eventing   kube-root-ca.crt                                       1      13m
kube-node-lease    kube-root-ca.crt                                       1      15m
...
```

**Comment by creydr** [comment]
Seems this comes, because the `kafka-source-dispatcher-0` does not get scaled back to 0 again. Could be related to https://github.com/knative/eventing/pull/7027 :thinking: 
Before I dig deeper into it: @pierDipi does this ring any bells on you?

**Comment by pierDipi** [comment]
Yes @creydr, I'm testing a patch for the autoscaler/scheduler, it takes some time since it's using our days long running tests

**Comment by creydr** [comment]
Latest changes did not fix it. Still having the kafka-source-dispatcher-0 not getting scaled back to 0 again. In addition I see these events: 

```
3m28s       Warning   FailedGetResourceMetric        horizontalpodautoscaler/eventing-webhook                    failed to get cpu utilization: unable to get metrics for resource cpu: unable to fetch metrics from resource metrics API: the server could not find the requested resource (get pods.metrics.k8s.io)
45m         Warning   FailedComputeMetricsReplicas   horizontalpodautoscaler/eventing-webhook                    invalid metrics (1 invalid out of 1), first error is: failed to get cpu resource metric value: failed to get cpu utilization: unable to get metrics for resource cpu: unable to fetch metrics from resource metrics API: the server could not find the requested resource (get pods.metrics.k8s.io)
```

**Comment by pierDipi** [comment]
I rebased the PR for another test run on top of the latest changes

**Comment by creydr** [comment]
@Cali0707 @matzew It finally passed :tada: 
Could you review?

/cc @pierDipi

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
