### PR TITLE
Expose test package to reuse

### PR DESCRIPTION
**Pull request by dsimansk**
Fixes #

## Proposed Changes

- Expose test package to reuse

I'd like to refactor `eventing-autoscaler-keda` to depend on `e-k-b` and remove `eventing-broker` from dependencies. Hence the test package is reused there.

### CODE REVIEW

**Comment by pierDipi** [comment]
> I'd like to refactor `eventing-autoscaler-keda` to depend on `e-k-b` and remove `eventing-broker` from dependencies. Hence the test package is reused there.

can you describe more about the why? Ideally, eventing-autoscaler-keda, doesn't have the integration with Kafka resources anymore as we're adding them in this repository

cc @Cali0707

**Comment by dsimansk** [comment]
> > I'd like to refactor `eventing-autoscaler-keda` to depend on `e-k-b` and remove `eventing-broker` from dependencies. Hence the test package is reused there.
> 
> can you describe more about the why? Ideally, eventing-autoscaler-keda, doesn't have the integration with Kafka resources anymore as we're adding them in this repository
> 
> cc @Cali0707

There's a smoke test setup, that uses old `e-k` bits. Perhaps the whole setups can be streamlined here?
https://github.com/knative-extensions/eventing-autoscaler-keda/blob/main/test/e2e/smoke_test.go#L51-L52

**Comment by dsimansk** [comment]
Streamline or maybe completely removed. It's really rather simplistic smoke test, as far as I can tell. :)

**Comment by dsimansk** [comment]
Maybe it will work even without the placeholder package. Either `Golang` or `Goland` is playing games with me. :)
/hold

**Comment by dsimansk** [comment]
It's not needed in such form.
/close

**Pull request closed without merging**
