### PR TITLE
Change the name of the secretVolumePath

### LINKED ISSUE #3302: Mistake in secretVolumePath
**Describe the bug**
https://github.com/Leo6Leo/eventing-kafka-broker/blob/3ccd420801ffb3a433a3806ed1d3df4a13d65a4a/data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/main/ReceiverVerticleFactory.java#L39

The name should be `etc/receiver-tls-secret` instead of `/etc/receiver-secret-volume`

### PR DESCRIPTION
**Pull request by Leo6Leo**
Fixes #3302

## Proposed Changes
The name should be etc/receiver-tls-secret instead of /etc/receiver-secret-volume

### CODE REVIEW

**Review by Cali0707 — APPROVED** [review]
/lgtm

**Review by matzew — APPROVED** [review]
/lgtm
/approve

/retest

**Pull request merged**
