### PR TITLE
Add broker OIDC e2e tests

### LINKED ISSUE #3684: [data-plane]: Add Broker OIDC e2e tests
With the Broker exposing its Audience (#3600) and Receiver & Dispatcher having the OIDC bits, we should run the Broker OIDC e2e tests.

This includes for example:
* `oidc.AddressableOIDCConformance()` to check if a broker exposes its audience and accepts only valid JWTs
* `brokerfeatures.BrokerSendEventWithOIDC()` to check if a broker sends authenticated events to subscriber/reply&DLS

### PR DESCRIPTION
**Pull request by creydr**
Fixes #3684

## Proposed Changes

- :gift: Add OIDC e2e tests for Broker

The call in reconciler-tests.sh to run the OIDC tests was added in #3675 already:
https://github.com/knative-extensions/eventing-kafka-broker/blob/d6a383fff58047078c232f83bdcbe9e88d402891/test/reconciler-tests.sh#L57-L61

### CODE REVIEW

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

If tests pass

**Comment by creydr** [comment]
OIDC tests were failing, because the kafka broker [template](https://github.com/knative-extensions/eventing-kafka-broker/blob/525c0d466d2f6d9746dd8cf56f67e47365c031a9/test/e2e_new/templates/kafka-broker/broker.yaml#L51-L67) did not contain a field for CACerts & audience spec in its DLS config. Added it in 77c9089df6ca7ded1d8298874add848964bbd554.

@pierDipi @Leo6Leo @Cali0707 could you recheck? :)

**Review by Cali0707 — APPROVED** [review]
/lgtm

**Pull request merged**
