### PR TITLE
Add eventing kafka broke reviewers role

### PR DESCRIPTION
**Pull request by Cali0707**
## Proposed Changes

- Add `eventing-kafka-broker-reviewers` role as reviewer to repository

### CODE REVIEW

**Comment by pierDipi** [comment]
The alias doesn't exist yet https://github.com/knative-extensions/eventing-kafka-broker/blob/a60586958fa6f8028624e7cd7e99731f00d738a3/OWNERS_ALIASES#L48-L51

should we create it first?

**Comment by Cali0707** [comment]
> The alias doesn't exist yet
> 
> https://github.com/knative-extensions/eventing-kafka-broker/blob/a60586958fa6f8028624e7cd7e99731f00d738a3/OWNERS_ALIASES#L48-L51
> 
> should we create it first?

@pierDipi I think I tried to create it in https://github.com/knative/community/pull/1428. Will that work or do I need to do something else as well?

**Comment by Cali0707** [comment]
@pierDipi the owners file is valid now :)

**Review by creydr — APPROVED** [review]
Got the alias in https://github.com/knative-extensions/eventing-kafka-broker/pull/3327/files :tada: 
/lgtm

**Pull request merged**
