### PR TITLE
Update dataplane dependencies

### PR DESCRIPTION
**Pull request by creydr**
Includes dependabot fixes with fixes of the build issues

* :broom: Bump micrometer to 1.11.5
* :broom: Bump ch.qos.logback.version to 1.4.11
* :broom: Bump jmh.version to 1.37
* :broom: Bump org.apache.maven.plugins:maven-enforcer-plugin to 3.4.1
* :broom: Bump maven-compiler-plugin to 3.11.0
* :broom: Update spotless to 2.38 and palantirJavaFormat to 2.38 to fix JDK 1.21 build issues
* :broom: Bump slf4j to 2.0.4 to fix build issues

### CODE REVIEW

**Comment by creydr** [comment]
infra test image is currently on java 20: https://github.com/knative/infra/blob/8dec87685869572f7dcac6312470be722afe208a/images/prow-tests/Dockerfile#L23

**Comment by Cali0707** [comment]
> infra test image is currently on java 20: https://github.com/knative/infra/blob/8dec87685869572f7dcac6312470be722afe208a/images/prow-tests/Dockerfile#L23

I think we should bump this to 21 after the release

**Review by Cali0707 — APPROVED** [review]
Seems to have tests passing after making the update
/lgtm

**Comment by creydr** [comment]
> > infra test image is currently on java 20: https://github.com/knative/infra/blob/8dec87685869572f7dcac6312470be722afe208a/images/prow-tests/Dockerfile#L23
> 
> I think we should bump this to 21 after the release

I agree. Just didn't want to have the bump before the 1.12 release...

**Pull request merged**
