### PR TITLE
Deprecate calling kubetest2 via kntest

### PR DESCRIPTION
**Pull request by upodroid**
Part of https://github.com/knative/hack/pull/230

/cc @matzew

### CODE REVIEW

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Comment by upodroid** [comment]
/retest


Test failures aren't related to my changes

**Comment by matzew** [comment]
@upodroid thanks!

the `loom_eventing` are expected to fail

**Comment by upodroid** [comment]
/override reconciler-tests-loom_eventing-kafka-broker_main

Unrelated failure

**Comment by upodroid** [comment]
btw, you can run the job without reporting it to GitHub. You'll have to open it in prow to see what happened

**Pull request merged**
